controllers/VendorController.php
<?php 
namespace app\controllers;

use Yii;
use yii\rest\ActiveController;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\EntryForm;
use app\models\BusinessDetailForm;
use app\models\VendorForm;
use yii\helpers\Json;
use PHPUnit\Framework\Constraint\Exception;
use PhpParser\JsonDecoder;
use Mpdf\Mpdf;
use yii\helpers\Url;

class VendorController extends Controller
{
// constant use in class
    const beforeschedulefns = 909;
    const scheduleFns       = 910;
    const visitFns          = 911;
    const dataEntryFns      = 912;
    const validationFns     = 913;
    const draftFns          = 914;
    const rejectFns         = 920;

// Index action is for Business Detail Page for capturing & validating data (according to permission) from user
    public function actionIndex(){
        try{
            $session = Yii::$app->session;
            $glId = Yii::$app->getRequest()->getQueryParam('glId');
            $woId = Yii::$app->getRequest()->getQueryParam('woId');
            $ak = Yii::$app->getRequest()->getQueryParam('akKey');
            $empId = Yii::$app->getRequest()->getQueryParam('empId');
            $empName = Yii::$app->getRequest()->getQueryParam('empName');
            $validate = Yii::$app->getRequest()->getQueryParam('validate');
            $fnsId = Yii::$app->getRequest()->getQueryParam('fnsId');
            
            $businessModel = new BusinessDetailForm();
            if(!empty($glId)){
                if($session->has('businessDetail')){
                    session_destroy(); 
                }
                $appointment = $businessModel->getAppointmentData(VendorController::visitFns,$woId); 
                $getBusinessDetail  =$this->getDetail($glId,$appointment[0]['CHKLST_ID'],8);    
                $businessDetail = $this->convertedData($getBusinessDetail['data']['records']);
                $sess['businessDetail'] = $businessDetail;
                // storing basic data in session
                $session->set('glId',$glId);
                $session->set('woId',$woId);
                $session->set('fnsId',$fnsId);
                $session->set('akKey',$ak);
                $session->set('empId',$empId);
                $session->set('empName',$empName);
                
                $session->set('businessDetail',$sess['businessDetail']);
            }else{
                $session = Yii::$app->session;
                if($session->has('businessDetail')){
                }
                else if(!empty($session['glId']) && !empty($session['woId'])){
                    $appointment = $businessModel->getAppointmentData(VendorController::visitFns,$session['woId']);
                    $getBusinessDetail  =$this->getDetail($session['glId'],$appointment[0]['CHKLST_ID'],8);
                    $businessDetail = $this->convertedData($getBusinessDetail['data']['records']);
                    $sess['businessDetail'] = $businessDetail;
                    $session->set('businessDetail',$sess['businessDetail']);
                }
                else{
                    Yii::$app->session->setFlash('error', "Session Expire."); 
                    return $this->redirect(['index']);
                }
            }
                if(!empty($validate)){
                    $session->set('validate',$validate);
                }else{
                    if(empty($session['validate'])){
                        $session->set('validate',1);
                    }
                }
            $rejectStatus = $businessModel->getStageStatus($session,VendorController::rejectFns);
            $validationStatus = $businessModel->getStageStatus($session,VendorController::dataEntryFns);
            $request = Yii::$app->request;
            if ($request->isPost) {
                $session = Yii::$app->session;
                $appointment = $businessModel->getAppointmentData(VendorController::visitFns,$session['woId']);
                $attributesName = $businessModel->getAttributeData(8);
                    $postData = Yii::$app->request->post(); //data from post method 
                    // echo '<pre>'; print_r($postData); die;
                    foreach($attributesName as $key=>$val){
                        if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='COMPANY_DETAIL'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['company_name'];
                            $attribute[$key]['entry_status']=$postData['COMPANY_DETAIL_status'];
                            $attribute[$key]['entry_comment']=$postData['COMPANY_DETAIL_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='TEL_NAME'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['tel_no'];
                            $attribute[$key]['entry_status'] =$postData['TEL_NAME_status'];
                            $attribute[$key]['entry_comment'] = $postData['TEL_NAME_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='FAX_NO'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['fax_no'];
                            $attribute[$key]['entry_status'] =$postData['FAX_NO_status'];
                            $attribute[$key]['entry_comment'] = $postData['FAX_NO_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='REGISTERED_OFFICE_ADDRESS'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['office_address'];
                            $attribute[$key]['entry_status'] =$postData['REGISTERED_OFFICE_ADDRESS_status'];
                            $attribute[$key]['entry_comment'] = $postData['REGISTERED_OFFICE_ADDRESS_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='MOBILE_NO'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['mob_no'];
                            $attribute[$key]['entry_status'] =$postData['MOBILE_NO_status'];
                            $attribute[$key]['entry_comment'] = $postData['MOBILE_NO_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='EMAIL'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['email'];
                            $attribute[$key]['entry_status'] =$postData['EMAIL_status'];
                            $attribute[$key]['entry_comment'] = $postData['EMAIL_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='MANUFACTURING_FACILITY'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['manufacturing_facilities'];
                            $attribute[$key]['entry_status'] =$postData['MANUFACTURING_FACILITY_status'];
                            $attribute[$key]['entry_comment'] = $postData['MANUFACTURING_FACILITY_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='WEBSITE'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['website'];
                            $attribute[$key]['entry_status'] =$postData['WEBSITE_status'];
                            $attribute[$key]['entry_comment'] = $postData['WEBSITE_comment'];
                        }else if($val['STS_ATTRIBUTE_DISPLAY_NAME']=='LIST_OF_BRANCHES'){
                            $attribute[$key]['attribute_id']=$val['GL_STS_ATTRIBUTE_ID'];
                            $attribute[$key]['attribute_value']=$postData['list_of_branches'];
                            $attribute[$key]['entry_status']  =$postData['LIST_OF_BRANCHES_status'];
                            $attribute[$key]['entry_comment'] = $postData['LIST_OF_BRANCHES_comment'];
                        }                        
                    }
                    $data['AK']=$session['akKey'];
                    $data['empid']=$session['empId'];
                    $postData['glid']= $session['glId'];
                    $postData['chklst_id']=$appointment[0]['CHKLST_ID'];
                    // $postData['chklst_id']=$session['woId'];
                    $url = 'http://dev-merp.intermesh.net/index.php/erp/Trustseal/UpdateTsVendorNew';
                    foreach($attribute as $key=>$val){
                        $update[$key]['attribute_id'] = $val['attribute_id'];
                        $update[$key]['attribute_value'] = $val['attribute_value'];
                        $update[$key]['entry_status'] = $val['entry_status'];
                        $update[$key]['entry_comment']= $val['entry_comment'];
                        $update[$key]['glid']         = $postData['glid'];
                        $update[$key]['chklst_id']    = $postData['chklst_id'];  
                        if($postData['submitVal']=='insert'){
                            $update[$key]['entry_status'] = 'p';
                        }
                    }
                    $getBusinessDetail  =$this->getDetail($glId,$woId,1);
                    if($postData['submitVal']=='update'){
                        $data['updateData'] = Json::encode($update, $asArray = true);
                    }else{
                        $data['insertData'] = Json::encode($update, $asArray = true);
                    }
                    // echo'<pre>'; print_r($data); die;

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

header('Access-Control-Allow-Origin: *'); 
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <!-- https://utils.imimg.com/imsrchui/js/jquery.js -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>    
    <SCRIPT TYPE="text/javascript" SRC="https://dev-utils.imimg.com/suggest/js/suggest.js"></SCRIPT>   
 
      
    <!-- <SCRIPT TYPE="text/javascript" SRC="https://utils.imimg.com/suggest/js/jq-ac-ui.js"></SCRIPT> -->
    <!-- <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js"></script> -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> -->
    <!-- <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script> -->
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    
</head>
<body>

<?php $this->beginBody() ?>

<div class="wrap" style="background-color: white;">
    <?php
    NavBar::begin([
        'brandLabel' => 'Trust Seal',
        // 'brandUrl' => '/',
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $session = Yii::$app->session;
    $userType = Yii::$app->getRequest()->getQueryParam('userType');
    if(!empty($userType)){
        $session['userType'] = $userType;
    }
    // echo '<pre>'; print_r($userType); die;
    if(!empty($session['userType'])){
        if($session['userType']==1){
            $menu = [
                ['label' => 'Scheduling', 'url' => ['/vendor/scheduling'] ,'options'=>['id'=>'schedulingList']],
                ['label' => 'Visit',      'url' => ['/vendor/visit'],'options'=>['id'=>'visitList']],
                ['label' => 'Data Entry', 'url' => ['/'],'options'=>['id'=>'indexList']],
            ];
        }else if($session['userType']==2){
            $menu = [
                ['label' => 'Validation', 'url' => ['/vendor/index'],'options'=>['id'=>'validationList']],
                ['label' => 'Draft',      'url' => ['/vendor/draft'],'options'=>['id'=>'draftList']],
            ];
        }else{
            $menu = [
                ['label' => 'Scheduling', 'url' => ['/vendor/scheduling'],'options'=>['id'=>'schedulingList']],
                ['label' => 'Visit',      'url' => ['/vendor/visit'],'options'=>['id'=>'visitList']],
                ['label' => 'Data Entry', 'url' => ['/'],'options'=>['id'=>'indexList']],
                ['label' => 'Validation', 'url' => ['/vendor/index'],'options'=>['id'=>'validationList']],
                ['label' => 'Draft',      'url' => ['/vendor/draft'],'options'=>['id'=>'draftList']],
            ];
        }
    }else{
        $menu = [
                ['label' => 'Scheduling', 'url' => ['/vendor/scheduling'],'options'=>['id'=>'schedulingList']],
                ['label' => 'Visit',      'url' => ['/vendor/visit'],'options'=>['id'=>'visitList']],
                ['label' => 'Data Entry', 'url' => ['/'],'options'=>['id'=>'indexList']],
                ['label' => 'Validation', 'url' => ['/vendor/index'],'options'=>['id'=>'validationList']],
                ['label' => 'Draft',      'url' => ['/vendor/draft'],'options'=>['id'=>'draftList']],
        ];
    } 
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => $menu,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>